### ISSUE TITLE
the dataset  url is not exist？

### ISSUE THREAD

**Issue by zhangcj13** [wangxiao5791509/VisEvent_SOT_Benchmark#2]
hi：
   i want to download the visevent dataset. but the dataset url link does not exist. can you provide the download link? thanks

**Comment by zhangcj13** [comment]
i found the download url in the a forked one

**Comment by wangxiao5791509** [comment]
@zhangcj13   
您好，数据集已更新到 百度云盘。请下载这个版本的（有对部分真值 bbox 进行调整）。

onedrive 版本快传好了。

**Comment by Carter-1998** [comment]
您好，请问应该如何解压数据集？（VisEvent_train.z04）直接修改后缀？

**Comment by Carter-1998** [comment]
您好，看到论文中，您对OTB和VOT两个基于帧的数据集进行了转化。为了公平的比较，能否麻烦您提供转化后的数据集呢？谢谢！

**Comment by wangxiao5791509** [comment]
@Carter-1998   在linux 系统下解压的话，估计需要现将文件合并为单个 zip 文件，再解压。类似这种：
cat filename.zip.0* > filename.zip
unzip filename.zip
其中 filename 为压缩文件名字。

如果是windows系统的话，试试直接用 zip 解压第一个文件，后续的文件软件会自动解压。

您提到的这个 VOT, OTB 仿真数据，不是真实 event 数据，可以不搞。建议就用 FE108 和  VisEvent 进行相关实验即可。

**Comment by wangxiao5791509** [comment]
@Carter-1998   emmmm，考虑了一下，还是决定将 VOT2019-RGB-EVENT 这个数据集传到百度云，将会很快更新链接。

**Comment by wangxiao5791509** [comment]
@Carter-1998   hi, try this

Link：https://pan.baidu.com/s/1cS79d1dJFD8mF0AwuGG5Og   Password: AHUT

**Comment by Carter-1998** [comment]
您好，请问在论文的描述中
![image](https://user-images.githubusercontent.com/40255107/183906110-f9b76ba2-3486-44d0-aec2-627352cd0a86.png)
这17个属性对应的序列分别是什么名称？
