### ISSUE TITLE
License information of the code and the dataset?

### ISSUE THREAD

**Issue by Rtakaha** [wangxiao5791509/VisEvent_SOT_Benchmark#4]
Hi, thank you for your great work!

I have one question, what is the license of the code and the dataset? I have checked the [website](https://sites.google.com/view/viseventtrack/), but could not find the information.

Thank you!

**Comment by wangxiao5791509** [comment]
@Rtakaha Hi, thanks for your kind reminder. I just updated the license information. Please check it from this link: https://github.com/wangxiao5791509/VisEvent_SOT_Benchmark/blob/main/License

**Comment by Rtakaha** [comment]
@wangxiao5791509 
Thank you very much! Now I understand both the code and the dataset is under MIT license.
