### ISSUE TITLE
How to unzip the .z01 .z02

### ISSUE THREAD

**Issue by laisimiao** [wangxiao5791509/VisEvent_SOT_Benchmark#6]
could you share the unzip scripts within download link and teach us how to unzip downloaded dataset.
Because I have tried `cat VisEvent_train.z* > Train.zip && unzip Train.zip` and it failed. It costs too much time and saving memory to do it again.
Therefore, if you could provide the right unzip script in ubuntu, it would be happy.

**Comment by laisimiao** [comment]
ok i solve it

**Comment by wangchao668** [comment]
> ok i solve it

how to solve it thank you
